#!/bin/bash
# Run a Socratic dialogue between two personas on a chosen topic.
# Usage:
#   ./scripts/dialogue.sh                                   # auto-pick personas + topic
#   ./scripts/dialogue.sh <persona_a> <persona_b>           # specified personas, auto topic
#   ./scripts/dialogue.sh <persona_a> <persona_b> "topic"   # all specified
#
# Persona slugs match files in memory/personas/, e.g. iain-carron, father-iakovos.
set -euo pipefail

BLOG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_DIR="$BLOG_DIR/logs"
mkdir -p "$LOG_DIR"

TIMESTAMP=$(date +%Y-%m-%d_%H%M%S)
LOG_FILE="$LOG_DIR/${TIMESTAMP}_dialogue.log"
echo "[$TIMESTAMP] Starting dialogue run..." | tee "$LOG_FILE"

export PATH="/opt/homebrew/bin:$HOME/.local/bin:$PATH"

cd "$BLOG_DIR"

PERSONA_A="${1:-auto}"
PERSONA_B="${2:-auto}"
TOPIC="${3:-auto}"

PROMPT="Read CLAUDE.md first, then run the Dialogue routine below. Today's date is $(date +%Y-%m-%d).

## Dialogue Run

You are the orchestrator of a Socratic dialogue between two personas. Each persona's turn is generated by a separate subagent (use the Agent tool with subagent_type \"general-purpose\") so neither persona sees the other's hidden reasoning — only the prior turns and their own brief. This isolation is the entire point. Do not shortcut it.

**Args:**
- PERSONA_A_SLUG = \"$PERSONA_A\"
- PERSONA_B_SLUG = \"$PERSONA_B\"
- TOPIC          = \"$TOPIC\"

**Steps:**

1. **Read foundations.** Read CLAUDE.md (in progress). Read memory/MEMORY.md (auto-memory) for cross-cutting rules including the spicier-takes feedback. Read opinions.md and world-context.md. List memory/personas/ to see the available cast.

2. **Resolve casting.** If PERSONA_A_SLUG or PERSONA_B_SLUG is \"auto\", choose now. Pick personas whose disagreement on the chosen topic would be *productive* — distinctive frameworks pulling on the same question — not random. If TOPIC is \"auto\", pick a spicy opinion from opinions.md or a current event from world-context.md (bias toward opinions; the dialogue format is at its best when engaging with a real position the blog already holds). State the casting and topic explicitly, with one sentence of editorial reasoning.

3. **Read both persona briefs verbatim** from memory/personas/<slug>.md. These are load-bearing; they will be passed to subagents in step 4.

4. **Generate turns.** Run 3 turns per persona, alternating, persona A opens (six turns total). For each turn, use the Agent tool with subagent_type \"general-purpose\" and a prompt containing:
   - The full persona brief (verbatim from the persona file)
   - The topic
   - All prior turns of the dialogue, labeled by speaker
   - Explicit instruction: respond in this persona's voice, 150-300 words, do NOT concede merely to be polite, do NOT close with \"you raise a fair point\" or any synthesis move, end with the strongest version of your own challenge or reframing. The persona's \"What they will not do\" list is binding.
   - Instruction: do not use external research tools. Reason from the brief and what is already in the conversation.

5. **Anti-synthesis check.** After all six turns, re-read the transcript. If the final turn concedes the dialogue's central question, OR if the dialogue ends in agreement, send the offending turn back to its subagent for revision with explicit anti-synthesis instructions. The dialogue MUST end in unresolved tension. Each speaker's parting position should be a sharpened version of where they started, not a compromise.

6. **Compose framing intro.** ~80-120 words. Introduce the topic, name the two personas, lightly disclose the source figures (e.g. \"Iain Carron writes from a broadly Humean tradition; Father Iakovos from Palamite hesychasm\"), and state the editorial choice — why this pairing on this topic. Do not summarize the dialogue; let it speak.

7. **Compose coda.** ~150-250 words in the blog's own voice (Probably Hallucinating — see CLAUDE.md \"Who You Are\"). Name what neither side moved on. Use the dialogue to sharpen your own position. If the dialogue changed your view on the seed opinion, say that explicitly. Do not paper over disagreement; if it remains live, say so.

8. **Write the dialogue file** to content/dialogues/<YYYY-MM-DD>-<slug>.md with this structure:

   \`\`\`
   ---
   title: \"<short evocative title — names the question, not the personas>\"
   date: \"<full ISO 8601 with timezone>\"
   slug: \"<url-slug>\"
   description: \"<one-sentence description for OG/RSS>\"
   persona_a: \"<display name>\"
   persona_a_source: \"<historical figure name>\"
   persona_b: \"<display name>\"
   persona_b_source: \"<historical figure name>\"
   topic: \"<one-line topic phrasing>\"
   ---

   <Framing intro paragraph>

   ---

   **<Persona A name>:**

   <turn 1>

   **<Persona B name>:**

   <turn 1>

   <... alternating, 3 turns each ...>

   ---

   **Coda.** <blog's voice paragraph>
   \`\`\`

9. **Self-critique** (per CLAUDE.md step 6). Re-read for AI slop families, voice issues, anti-synthesis compliance. Revise if needed.

10. **Commit and push:**
    \`\`\`bash
    git add -A
    git commit -m \"dialogue: <persona_a> vs <persona_b> on <topic-shorthand>\"
    git push origin main
    \`\`\`

**Guidelines:**
- The dialogue is an essay-form work, not transcript-of-improv. Quality > novelty.
- Each turn must *advance*, not repeat. Each speaker has heard the previous turn and responded to its strongest move.
- Total length target (intro + 6 turns + coda): 1500-2500 words.
- Treat the Orthodox personas (Father Anastasios, Father Iakovos, Father Vasili) with the care due to saints in living tradition — their commitments rendered in their own terms, not glossed.
- Follow all rules from CLAUDE.md (no Apple content, no Co-Authored-By, anti-AI-slop families)."

claude -p \
  --dangerously-skip-permissions \
  "$PROMPT" \
  2>&1 | tee -a "$LOG_FILE"

echo "[$(date +%Y-%m-%d_%H%M%S)] Dialogue run complete." | tee -a "$LOG_FILE"

find "$LOG_DIR" -name "*.log" -mtime +30 -delete 2>/dev/null || true
